#!/usr/bin/env python3
"""Check an IIT answer against the corpus Q&A voice.

Usage:
    python check_answer.py answer.md
    cat answer.md | python check_answer.py
    python check_answer.py answer.md --anchor haun-2019 --wiki wiki-overview
    python check_answer.py answer.md --json
    python check_answer.py --list-anchors

Reports sentence-length statistics against the style anchor chosen for the
question (a corpus paper or wiki page, see references/style-anchors.md) and
the wiki FAQ profile, plus the share of the answer in list items, bold
density, arrow chains, and hits from the banned vocabulary. It is a prompt to
reread, not a score to optimize.
"""
import sys, os, re, json, statistics, argparse

# Sentence profiles of the corpus sources, measured with sentence_lengths()
# below on cleaned texts of the sources
# (references stripped). Keys are IIT Expert slugs, or wiki-<page>. "faq" is
# the five wiki FAQ pages combined.
_HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_HERE, "profiles.json"), encoding="utf-8") as _f:
    PROFILES = json.load(_f)
FUNCTION_WORDS = set("the of and to is in that are be by as it this which".split())

CHAT_FRAMING = [
    "great question", "short answer", "tl;dr", "in a nutshell", "let's break",
    "let me break", "here's the key", "the key insight", "it's worth noting",
    "bottom line", "to put it simply", "key takeaway",
]
NARRATOR = [
    r"\bthis is the (crux|key move|point|twist|upshot|insight)\b",
    r"\bhere is the (crux|twist|catch)\b",
]
# Sentences about the answer's own structure rather than about the theory.
# Observed in test answers; the corpus's transitions carry content instead.
META = [
    r"\b(same|this) (template|recipe|pattern|playbook|method) (carries over|applies|repeats|recurs)",
    r"\bshows the method at work\b",
    r"\b(two|three|several) (features|things|points|aspects|moves) (set|make|distinguish)\b",
    r"\b(one|a) (consequence|point|subtlety|implication) (is|that is) (easy to miss|worth)",
    r"\bis the surest way to\b",
    r"\bthe answer (it|IIT) (arrives at|gives|reaches)\b",
    r"\bthis is (the crux|the key|where it gets)\b",
]
APPARATUS = r"\b(eq\.?|eqn\.?|equation|fig\.?|figure|supplement(ary)?|S\d text|section) ?\(?\d"
AI_VOCAB = [
    "delve", "tapestry", "landscape", "realm", "navigate", "unlock", "harness",
    "leverage", "robust", "seamless", "holistic", "multifaceted",
    "groundbreaking", "shed light on", "a testament to", "plays a crucial role",
    "plays a vital role", "it is important to note", "objective correlate",
    "best explanation",
]
# Fine when negated ("does not emerge from"); flagged so the context gets a look.
CHECK_CONTEXT = ["emerges from", "emerge from", "generated by", "produced by"]


def strip_markdown(text):
    text = re.sub(r"```.*?```", " ", text, flags=re.S)          # code blocks
    text = re.sub(r"\$\$.*?\$\$", " ", text, flags=re.S)         # display math
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)        # links -> text
    text = re.sub(r"^\s*#.*$", " ", text, flags=re.M)             # headings
    text = re.sub(r"^\s*\|.*\|\s*$", " ", text, flags=re.M)       # tables
    text = re.sub(r"[*_`>]", "", text)
    return text


def sentence_lengths(text):
    prose = strip_markdown(text)
    prose = re.sub(r"^\s*([-*+]|\d+[.)])\s+", "", prose, flags=re.M)
    prose = re.sub(r"\s+", " ", prose)
    out = []
    for s in re.split(r"(?<=[.!?])\s+(?=[A-Z\"“(])", prose):
        words = re.findall(r"[A-Za-zΦφ][\w'’\-–]*", s)
        if len(words) < 2 or len(words) > 120:
            continue
        # skip figure labels, headers and other non-sentences
        if len(words) > 3 and not FUNCTION_WORDS & {w.lower() for w in words}:
            continue
        out.append(len(words))
    return out


def analyze(text):
    lines = [l for l in text.splitlines() if l.strip()]
    list_lines = [l for l in lines if re.match(r"^\s*([-*+]|\d+[.)])\s+", l)]
    words_total = len(re.findall(r"\w+", strip_markdown(text)))
    words_in_lists = sum(len(re.findall(r"\w+", strip_markdown(l))) for l in list_lines)
    bold = len(re.findall(r"\*\*[^*]+\*\*", text))
    bold_label_bullets = len([l for l in list_lines if re.match(r"^\s*([-*+]|\d+[.)])\s+\*\*[^*]+\*\*\s*[:—–-]", l)])
    arrows = len(re.findall(r"→|->|⇒", strip_markdown(text)))
    headings = len(re.findall(r"^\s*#+\s", text, flags=re.M))

    low = text.lower()
    hits = {}
    for w in CHAT_FRAMING + AI_VOCAB:
        n = len(re.findall(r"\b" + re.escape(w) + r"\b", low))
        if n:
            hits[w] = n
    context = {}
    for w in CHECK_CONTEXT:
        n = len(re.findall(r"\b" + re.escape(w) + r"\b", low))
        if n:
            context[w] = n
    meta = []
    for s in re.split(r"(?<=[.!?])\s+", strip_markdown(text)):
        if any(re.search(p, s, re.I) for p in META):
            meta.append(s.strip()[:140])
    # Locators inside a citation's parentheses are required; count only those in the prose.
    prose = re.sub(r"\([^()]*\)", "", re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text))
    apparatus = len(re.findall(APPARATUS, prose, re.I))
    for pat in NARRATOR:
        n = len(re.findall(pat, low))
        if n:
            hits[pat] = n

    lens = sentence_lengths(text)
    stats = {}
    if lens:
        mean = statistics.mean(lens)
        sd = statistics.pstdev(lens) if len(lens) > 1 else 0.0
        stats = {
            "sentences": len(lens),
            "mean_words": round(mean, 1),
            "median_words": statistics.median(lens),
            "burstiness": round(sd / mean, 2) if mean else 0.0,
            "short_le8_pct": round(100 * sum(l <= 8 for l in lens) / len(lens)),
            "long_ge35_pct": round(100 * sum(l >= 35 for l in lens) / len(lens)),
        }

    return {
        "words": words_total,
        "sentence_stats": stats,
        "list_word_share_pct": round(100 * words_in_lists / words_total) if words_total else 0,
        "list_items": len(list_lines),
        "bold_label_bullets": bold_label_bullets,
        "bold_spans": bold,
        "arrows": arrows,
        "headings": headings,
        "banned_hits": hits,
        "check_context": context,
        "meta_sentences": meta,
        "apparatus_refs": apparatus,
    }


def notes(r, anchor="faq"):
    out = []
    s = r["sentence_stats"]
    a = PROFILES.get(anchor, PROFILES["faq"])
    if s:
        # journal PDFs inflate burstiness with extraction fragments; clean corpus
        # text (Tononi & Boly 2025, the wiki) sits at 0.45-0.65, so cap the target
        target = min(a["burst"], 0.65)
        if s["sentences"] >= 8 and s["burstiness"] < target - 0.2:
            out.append(f"rhythm is flatter than {anchor} (burstiness {s['burstiness']} vs {target}): "
                       "add short plain sentences among the long ones")
        if s["mean_words"] < a["mean"] - 7:
            out.append(f"sentences are short for {anchor} ({s['mean_words']} vs {a['mean']} words): "
                       "fragments or telegraphic style?")
        if s["mean_words"] > a["mean"] + 10:
            out.append(f"sentences are long for {anchor} ({s['mean_words']} vs {a['mean']} words)")
    if r["list_word_share_pct"] > 35:
        out.append(f"{r['list_word_share_pct']}% of the words are in list items: prose is the default")
    if r["bold_label_bullets"]:
        out.append(f"{r['bold_label_bullets']} bold-label bullets (\"**Label:** fragment\")")
    if r["bold_spans"] > max(2, r["words"] // 250):
        out.append(f"{r['bold_spans']} bold spans: keep bold to the central claim")
    if r["arrows"]:
        out.append(f"{r['arrows']} arrow(s): write the relation as a sentence")
    if r["banned_hits"]:
        out.append("banned vocabulary: " + ", ".join(f"{k} ×{v}" for k, v in r["banned_hits"].items()))
    for m in r["meta_sentences"]:
        out.append(f"sentence about the answer, not the theory: \"{m}\"")
    if r["apparatus_refs"]:
        out.append(f"{r['apparatus_refs']} equation/figure/section reference(s): put the locator in the citation, not the prose")
    if r["check_context"]:
        out.append("check these are negated or quoted: " + ", ".join(f"{k} ×{v}" for k, v in r["check_context"].items()))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("path", nargs="?")
    ap.add_argument("--anchor", default="faq", help="profile key of the style anchor paper")
    ap.add_argument("--wiki", default=None, help="profile key of the matching wiki page")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--list-anchors", action="store_true")
    a = ap.parse_args()
    if a.list_anchors:
        for k, v in sorted(i for i in PROFILES.items() if not i[0].startswith("_")):
            print(f"{k:45} mean {v['mean']:5} burstiness {v['burst']:5} short {v['short']:3}% long {v['long']:3}%")
        return
    for k in (a.anchor, a.wiki):
        if k and k not in PROFILES:
            sys.exit(f"unknown profile '{k}'; run --list-anchors")
    text = open(a.path, encoding="utf-8").read() if a.path else sys.stdin.read()
    r = analyze(text)
    r["anchor"], r["wiki"] = a.anchor, a.wiki
    r["notes"] = notes(r, a.anchor)
    if a.json:
        print(json.dumps(r, indent=2, ensure_ascii=False))
        return
    s = r["sentence_stats"]
    print(f"words {r['words']} | headings {r['headings']} | list items {r['list_items']} "
          f"({r['list_word_share_pct']}% of words) | bold {r['bold_spans']} | arrows {r['arrows']}")
    if s:
        print(f"sentences {s['sentences']} | mean {s['mean_words']} | median {s['median_words']} | "
              f"burstiness {s['burstiness']} | short {s['short_le8_pct']}% | long {s['long_ge35_pct']}%")
        for k in dict.fromkeys([a.anchor, a.wiki, "faq"]):
            if k:
                v = PROFILES[k]
                print(f"  vs {k}: mean {v['mean']} | burstiness {v['burst']} | short {v['short']}% | long {v['long']}%")
    print("notes:" if r["notes"] else "notes: none")
    for n in r["notes"]:
        print("  - " + n)


if __name__ == "__main__":
    main()
